<a href="https://colab.research.google.com/github/omonigho-egbo-15/-04NPY-Lab-Assignment/blob/main/npy_egboomonigho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## (04NPY) Lab Assignment Instructions Template - Working with NumPy ##

**Q01. Import NumPy package as np**
*(HINT: make sure to run the code cell after importing np)*

In [ ]:
import numpy as np

**Q02. Do the following in the same code cell:**

**A. Create a random number generator named rng with seed=12345**
*(HINT: use np.random modules' default_rng method)*

**B. Create a 3x4 two-dimensional array named M with 12 random integers between 0-10**
*(HINT: use rng's integers method with size argument set appropriately)*

**C. Display array M**
*(HINT: print statements)*

***Output Screenshot to verify:**

In [ ]:
rng = np.random.default_rng(12345)
M = rng.integers(0, 11, size=(3, 4))
print(M)

[[ 7  2  8  3]
 [ 2  8  7  7]
 [10  4  9  3]]


**Q03. Display the total and average of array M elements**
*(HINT: use sum and mean functions)*

***Output:***

In [ ]:
total_M = np.sum(M)
average_M = np.mean(M)
print(f"Total of M elements: {total_M}")
print(f"Average of M elements: {average_M}")

Total of M elements: 70
Average of M elements: 5.833333333333333


**Q04. Display the smallest and largest element within each column of array M**
*(HINT: use min and max functions with axis argument set appropriately)*

***Output:***

In [ ]:
smallest_elements_col = np.min(M, axis=0)
largest_elements_col = np.max(M, axis=0)
print(f"Smallest elements in each column of M: {smallest_elements_col}")
print(f"Largest elements in each column of M: {largest_elements_col}")

Smallest elements in each column of M: [2 2 7 3]
Largest elements in each column of M: [10  8  9  7]


**Q05. Display how many elements are greater than 5 and less than or equal to 9 in each row of array M**
*(HINT: use np.count_nonzero or np.sum function with relational operators and axis argument set appropriately)*

***Output:***

In [ ]:
count_elements = np.count_nonzero((M > 5) & (M <= 9), axis=1)
print(f"Number of elements greater than 5 and less than or equal to 9 in each row: {count_elements}")

Number of elements greater than 5 and less than or equal to 9 in each row: [2 3 1]


**Q06. Display the first, last, and second to last element of array M**
*(HINT: use fancy indexing)*

***Output:***

In [ ]:
first_element = M.flat[0]
last_element = M.flat[-1]
second_to_last_element = M.flat[-2]

print(f"First element of M: {first_element}")
print(f"Last element of M: {last_element}")
print(f"Second to last element of M: {second_to_last_element}")

First element of M: 7
Last element of M: 3
Second to last element of M: 9


**Q07. Display array M reversed**
*(HINT: use array slicing)*

***Output:***

In [ ]:
print(M[::-1])

[[10  4  9  3]
 [ 2  8  7  7]
 [ 7  2  8  3]]


**Q08. Display array M partitioned, where the first slot in each row contains the smallest element from that row**
*(HINT: use np.partition function with axis argument set appropriately)*

***Output:***

In [ ]:
partitioned_M = np.partition(M, 0, axis=1)
print(partitioned_M)

[[ 2  3  7  8]
 [ 2  7  7  8]
 [ 3  4  9 10]]


**Q09. Sort array M by each column in place and display**
*(HINT: use sort function with axis argument set appropriately)*

***Output:***

In [ ]:
M.sort(axis=0)
print(M)

[[ 2  2  7  3]
 [ 7  4  8  3]
 [10  8  9  7]]


**Q10. Create and display a 3x4 two-dimensional integer array named Z filled with 0's**
*(HINT: use np.zeros function with dtype argument and reshape function)*

***Output:***

In [ ]:
Z = np.zeros((3, 4), dtype=int)
print(Z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**Q11. Compute the squares of array M elements and store the results of computation into array Z and display array Z**
*(HINT: use np.power method with out argument set appropriately)*

***Output:***

In [ ]:
np.power(M, 2, out=Z)
print(Z)

[[  4   4  49   9]
 [ 49  16  64   9]
 [100  64  81  49]]


**Q12. Create a 3x4 two-dimensional integer array named B filled with numbers 0-11**
*(HINT: use np.arange function with dtype argument and reshape function)*

***Output:***

In [ ]:
B = np.arange(12, dtype=int).reshape(3, 4)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q13. Fill array B with 1's as a border and 0's inside and display the array**
*(HINTS: use np.ones with dtype argument set appropriately and slicing)*

***Output:***


In [ ]:
B = np.ones(B.shape, dtype=int)
B[1:-1, 1:-1] = 0
print(B)

[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]


**Q14. Display how many 0's and 1's exists in array B**
*(HINT: Use np.sum and relational operator ==)*

***Output:***

In [ ]:
num_zeros = np.sum(B == 0)
num_ones = np.sum(B == 1)
print(f"Number of 0's in array B: {num_zeros}")
print(f"Number of 1's in array B: {num_ones}")

Number of 0's in array B: 2
Number of 1's in array B: 10


**Q15. Create and display an empty container for structured array named SA with the following names and formats**
*(HINT: use np.zeros and np.dtype methods)*

    names: player, age, height
    formats: string, int, float

***Output:***

In [ ]:
dt = np.dtype([('player', 'U10'), ('age', 'i4'), ('height', 'f8')])
SA = np.zeros((4,), dtype=dt)
print(SA)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


**Q16. Fill the data below into array SA and display the array**
*(HINT: use lists and structured array indexing by names)*

    players = Matt, Mike, Mary, Mia
    age = 33, 21, 18, 19
    height = 6, 6.2, 5.8, 5.2

In [ ]:
players = ['Matt', 'Mike', 'Mary', 'Mia']
age = [33, 21, 18, 19]
height = [6.0, 6.2, 5.8, 5.2]

SA['player'] = players
SA['age'] = age
SA['height'] = height

print(SA)

[('Matt', 33, 6. ) ('Mike', 21, 6.2) ('Mary', 18, 5.8) ('Mia', 19, 5.2)]


**Q17. Find and display player(s) 6ft and above from structured array SA**
*(HINT: use structured array indexing and relational operator)*

In [ ]:
players_6ft_and_above = SA[SA['height'] >= 6.0]
print(f"Players 6ft and above: {players_6ft_and_above}")

Players 6ft and above: [('Matt', 33, 6. ) ('Mike', 21, 6.2)]


**Q18. View and display the above data as a record array named RA**
*(HINT: Use structured array SA.view method with np.recarray argument)*


In [ ]:
RA = SA.view(np.recarray)
print(RA)

[('Matt', 33, 6. ) ('Mike', 21, 6.2) ('Mary', 18, 5.8) ('Mia', 19, 5.2)]


**Q19. Display age of all players from record array RA**
*(HINT: print the age from RA)*

In [ ]:
print(RA.age)

[33 21 18 19]


**Q20. Find and display how many players are under 21 in record array RA**
*(HINT: use np.sum function making sure age field from RA is less than 21)*


In [ ]:
num_players_under_21 = np.sum(RA.age < 21)
print(f"Number of players under 21 in RA: {num_players_under_21}")

Number of players under 21 in RA: 2
